name: Webpage builder

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: sudosubin/git-clone-action@v1
        with:
          repository: 'mattjoke/TIM3D-web'
          ref: web

      - name: Install and Build project 🔧
        run: |
          npm install
          npm run build
        working-directory: web

      - name: Deploy webpage 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build # The branch the action should deploy to.
          folder: ~/web/public/ # The folder the action should deploy.
          target-folder: docs/
